# Generated by Django 4.0.1 on 2022-01-20 14:14

from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название жанра')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип носителя')),
            ],
            options={
                'verbose_name': 'Тип носителя',
                'verbose_name_plural': 'Тип носителей',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Писатель')),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Описание')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.uploading.upload_function)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название книги')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('slug', models.SlugField()),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Описание')),
                ('stock', models.IntegerField(default=1, verbose_name='Наличие')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('offer_of_the_week', models.BooleanField(default=False, verbose_name='Предолжение недели?')),
                ('image', models.ImageField(upload_to=utils.uploading.upload_function)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.genre')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.mediatype', verbose_name='Носитель')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.writer', verbose_name='Писатель')),
            ],
        ),
    ]
